name: Deploy to Magalu Cloud

on:
  push:
    branches:
      - main
      - criacao-cd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar conexão SSH
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      # 3. Verificar e instalar o Docker na VM remota
      - name: Verify and install Docker
        run: |
          ssh "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "
            if ! command -v docker > /dev/null; then
              echo 'Docker not found. Installing...';
              curl -fsSL https://get.docker.com -o get-docker.sh;
              sh get-docker.sh;
              sudo usermod -aG docker \$USER;
              echo 'Docker installed.';
            else
              echo 'Docker is already installed.';
            fi
          "

      # 4. Buildar a imagem Docker e criar uma tag
      - name: Build and Tag Docker Image
        run: |
          # Cria o diretório project no servidor remoto se não existir
          echo "Criando o diretório 'project' no servidor remoto..."
          ssh "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "mkdir -p ~/project"
          echo "Diretório 'project' criado ou já existente no servidor remoto."

          # Copia os arquivos do repositório para o diretório project
          echo "Copiando arquivos para o servidor remoto..."
          scp -r ./ ${SSH_USER}@${SSH_HOST}:~/project
          if [ $? -ne 0 ]; then
            echo "Erro ao transferir os arquivos com SCP!"
            exit 1
          fi
          echo "Arquivos copiados com sucesso para o servidor remoto."

          # Construa a imagem Docker no diretório project
          echo "Construindo a imagem Docker no servidor remoto..."
          ssh "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "
            cd ~/project;
            docker build -t bola-na-rede:0.0.1 .;
            if [ \$? -ne 0 ]; then
              echo 'Erro ao construir a imagem Docker!';
              exit 1;
            fi
            echo 'Imagem Docker construída com sucesso!';
          "
      

      # 5. Subir o container
      - name: Run Docker Container
        run: |
          ssh "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "
            docker stop bola-na-rede || true && docker rm bola-na-rede || true;
            docker run -d --name bola-na-rede -p 8080:8080 bola-na-rede:0.0.1;
          "
